# 使用动态数据源则用下面的配置,并且要在启动类上加(exclude = {DruidDataSourceAutoConfigure.class})
spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  # database 外网配置
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/cloud_user?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
  druid:
    #最大连接数
    max-active: 10
    #初始化连接数
    initial-size: 5
    #最小连接数
    min-idle: 5
    #配置获取连接等待超时的时间
    max-wait: 10000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    #这里建议配置为TRUE，防止取到的连接不可用
    test-on-borrow: true
    test-on-return: false
    #验证连接有效与否的SQL，不同的数据配置不同
    validation-query: SELECT 'x'
    # PSCache对支持游标的数据库性能提升巨大 ，mysql 建议关闭
    max-pool-prepared-statement-per-connection-size: 20
    pool-prepared-statements: false

  redisson:
    address: 127.0.0.1:6379
    timeout: 3000
    database: 0
    pool:
      max-active: 20
      max-idle: 10
      max-wait: 3000
      min-idle: 4
    password: